spring:
  application:
    name: performance-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/performancedb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc.batch_size: 50
        order_inserts: true
        order_updates: true
    open-in-view: false
  sql:
    init:
      mode: always
  mvc:
    cors:
      mappings:
        "/**":
          allowed-origin-patterns: "http://localhost:*,http://127.0.0.1:*,http://[::1]:*"
          allowed-methods: "GET,POST,PUT,DELETE,OPTIONS,PATCH"
          allowed-headers: "*"
          exposed-headers: "*"
          allow-credentials: true
          max-age: 3600

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO


